### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by joewiz** [wolfgangmm/atom-existdb#17]
[Enter steps to reproduce:]

1. Add a project without a .existdb.json file (via File > Add Project)
2. Select Packages > existdb > Edit Configuration for the Current Project - and see the error.

I expected either (a) a message saying that there is no configuration available for the current project and/or (b) opening a blank configuration file. 

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [existdb](https://github.com/wolfgangmm/atom-existdb) package 0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/joe/.atom/packages/existdb/lib/project-config.coffee:36

TypeError: Cannot read property 'getPath' of undefined
    at /packages/existdb/lib/project-config.coffee:36:48)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:21.3.0 settings-view:open (atom-pane.pane.active)
     -0:12.6.0 existdb:create-configuration-for-selected (span.name.icon.icon-repo)
     -0:05.7.0 existdb:create-configuration-for-current (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
existdb 0.4.1 
hyperclick 0.0.40 
linter 1.11.23 
```

**Comment by joewiz** [comment]
In fact, the docs say (b) is what should happen:

> Next, right click on the project root in the file tree and select Edit Configuration for Current Project (or use the existdb package menu). This creates a configuration file called .existdb.json in your project root.

When I select this (right-clicking on the top level of the Project Folder > eXistdb > Edit Configuration for project), nothing happens. This is why I tried the Packages > existdb route.

**Comment by rpsoft** [comment]
I'm also getting this issue

**Comment by joewiz** [comment]
Confirmed this still affects the development version of this app along with the current stable version of Atom.

**Comment by duncdrum** [comment]
yup was just testing this:
Atom: 1.18.0
OS: macOS 10.12.5
eXist-db 3.1.1
atom-server-side 0.2.7

**Comment by joewiz** [comment]
I can confirm that https://github.com/wolfgangmm/atom-existdb/commit/636d64dbfb23acf23142539c013ae8e9fcd95fb2 fixes this issue. Thanks @wolfgangmm!
