### ISSUE TITLE
ODD files assigned wrong mime type when uploaded via Project pane

### ISSUE THREAD

**Issue by joewiz** [wolfgangmm/atom-existdb#20]
See http://markmail.org/message/vq4yvjbs5gz2466x:

> I can confirm it is atom's upload function!
> 
> 1 select odd on filesystem
> 2 select odd folder in db
> 3 choose upload
> 4 try to recompile => fails

**Comment by joewiz** [comment]
Thanks! 

@eduarddrenth This should fix the issue you reported back in March (http://markmail.org/message/vq4yvjbs5gz2466x).

**Comment by eduarddrenth** [comment]
Great work, thanks!
