### ISSUE TITLE
High CPU usage even when idle

### ISSUE THREAD

**Issue by joewiz** [wolfgangmm/atom-existdb#22]
Whenever I have a project open with a `.existdb.json` file, the `atom-existdb` process regularly runs in excess of 120% CPU usage (on a quad-core 3.4 GHz Intel Core i7):

> ![screen shot 2017-06-10 at 6 04 36 pm](https://user-images.githubusercontent.com/59118/27006646-83275a94-4e07-11e7-99ae-7a9a9c311079.png)

- macOS 10.12.5
- atom 1.17.2
- atom-existdb master (b993f7bd00b2c62ca32d32fc4f6a6cf51f128a31)

I wonder if there's a way to reduce the CPU usage of the listener?

**Comment by duncdrum** [comment]
I can see that as well, but atom in general is quite CPU hungry

**Comment by joewiz** [comment]
CPU usage has actually gotten much better in the develop branch since I filed the issue. I think Wolfgang upgraded the library that watches the file system for changes. If you're seeing what I was seeing, can you add your relevant version numbers, etc.?

**Comment by duncdrum** [comment]
@joewiz I just installed a number of updates to atom, and i no longer see high CPU, or a separate ``atom-existdb`` thread at all. However, my ``.existdb.json`` file doesn't seem to work, neither does manual uploading of a resource (right-click -> upload resource).  
Atom: 1.18.0
OS: macOS 10.12.5
eXist-db 3.1.1
atom-server-side 0.2.7

**Comment by duncdrum** [comment]
all green from me, .existdb.json files are working again, and no excessive CPU
