### ISSUE TITLE
atom-existdb process does not quit, respawns upon restart

### ISSUE THREAD

**Issue by joewiz** [wolfgangmm/atom-existdb#8]
Steps to reproduce (assumes Atom 1.9.8 and atom-existdb 0.3.3 installed via Atom's package manager):
1. Start atom
2. Quit atom
3. atom-existdb remains in Activity Monitor

Repeating 5x yields 5 atom-existdb processes:

> ![screen shot 2016-08-11 at 1 30 00 pm](https://cloud.githubusercontent.com/assets/59118/17598284/bfe5a744-5fc7-11e6-8da6-c16e605ad440.png)

**Comment by joewiz** [comment]
I just confirmed the issue is still present with the current versions, Atom 1.12.6 and atom-existdb 0.3.3 (installed via Preferences > Install, not built from source). I'd be happy to test or provide more info, etc.

**Comment by duncdrum** [comment]
cannot reproduce this any longer with atom-existd 0.4.1, seems fixed.

**Comment by joewiz** [comment]
I'll check too, but to confirm, which OS and version are you using?

**Comment by duncdrum** [comment]
macOS 10.12.3 atom 1.14.3

**Comment by joewiz** [comment]
Okay, I've just checked - using the same OS and versions, in fact - and confirmed that the problem is no longer present. Upon quitting Atom, all Atom-related processes are liquidated.
